/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    BottomTabBar: typeof import('./src/components/BottomTabBar.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    GlassCard: typeof import('./src/components/GlassCard.vue')['default']
    RecipeCard: typeof import('./src/components/RecipeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
